{
 "title": "PostgreSQLDetails",
 "tags": [ "vendor=crunchydata" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "pg_up" } },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values({pg_cluster=\"$cluster\"},pod)"
    }
   },
   {
    "name": "datname",
    "label": "Database",
    "query": {
     "query": "label_values({pg_cluster=\"$cluster\",pod=~\"$pod\"},dbname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$cluster : Backup Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "min(ccp_backrest_last_incr_backup_time_since_completion_seconds{pg_cluster=\"$cluster\"} < ccp_backrest_last_diff_backup_time_since_completion_seconds{pg_cluster=\"$cluster\"} or ccp_backrest_last_incr_backup_time_since_completion_seconds{pg_cluster=\"$cluster\"} < ccp_backrest_last_full_backup_time_since_completion_seconds{pg_cluster=\"$cluster\"} or ccp_backrest_last_incr_backup_time_since_completion_seconds{pg_cluster=\"$cluster\"}) "
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{pg_cluster=\"$cluster\",pod=~\"$pod\",datname=~\"$datname\", state=\"active\"})*100 /sum(pg_settings_max_connections{pg_cluster=\"$cluster\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Idle In Transaction",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{pg_cluster=\"$cluster\",pod=~\"$pod\",datname=~\"$datname\",state=\"idle in transaction\"})/sum(pg_settings_max_connections{pg_cluster=\"$cluster\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Max Idle In Transaction Time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(abs(ccp_connection_stats_max_idle_in_txn_time{pg_cluster=\"$cluster\",pod=~\"$pod\"}))"
    }
   ]
  },
  {
   "title": "Idle",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{pg_cluster=\"$cluster\",pod=~\"$pod\",datname=~\"$datname\",state=\"idle\"})*100/sum(pg_settings_max_connections{pg_cluster=\"$cluster\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "% Toward Wraparound",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ccp_transaction_wraparound_percent_towards_wraparound{pg_cluster=\"$cluster\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ccp_stat_database_blks_hit{pg_cluster=\"$cluster\",pod=~\"$pod\"})*100/sum(ccp_stat_database_blks_hit{pg_cluster=\"$cluster\",pod=~\"$pod\"}+ccp_stat_database_blks_read{pg_cluster=\"$cluster\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Activity -  $pod-$datname",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ccp_stat_database_xact_commit{pg_cluster=\"$cluster\",pod=~\"$pod\",datname=~\"$datname\"}[5m])) + sum(irate(ccp_stat_database_xact_rollback{pg_cluster=\"$cluster\",pod=~\"$pod\",datname=~\"$datname\"}[5m]))",
     "legendFormat": "Transactions"
    },
    {
     "expr": "sum(irate(ccp_pg_stat_statements_total_calls_count{pg_cluster=\"$cluster\",pod=~\"$pod\",datname=~\"$datname\"}[5m]))",
     "legendFormat": "Queries"
    }
   ]
  },
  {
   "title": "Connections -  $pod-$datname",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (state) (pg_stat_activity_count{pg_cluster=\"$cluster\",pod=~\"$pod\",datname=~\"$datname\",state=\"idle\"})",
     "legendFormat": "idle"
    },
    {
     "expr": "sum by (state) (pg_stat_activity_count{pg_cluster=\"$cluster\",pod=~\"$pod\",datname=~\"$datname\",state=\"idle in transaction\"})",
     "legendFormat": "Idle in txn"
    },
    {
     "expr": "sum by (state) (pg_stat_activity_count{pg_cluster=\"$cluster\",pod=~\"$pod\",datname=~\"$datname\",state=\"active\"})",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "database size - $pod-$datname",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(ccp_database_size_bytes{pg_cluster=\"$cluster\",pod=~\"$pod\"})/(1024*1024)",
     "legendFormat": "Total : $cluster-$pod"
    },
    {
     "expr": "ccp_database_size_bytes{pg_cluster=\"$cluster\",pod=~\"$pod\",dbname=~\"$datname\"}/(1024*1024)",
     "legendFormat": "{{dbname}} ({{pod}})"
    }
   ]
  },
  {
   "title": "Query Duration - $pod-$datname",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(ccp_pg_stat_statements_total_mean_exec_time_ms{pg_cluster=\"$cluster\",pod=~\"$pod\", dbname=~\"$datname\"}) without (instance,ip)",
     "legendFormat": "Avg: {{exported_role}}({{dbname}})"
    },
    {
     "expr": "max(ccp_pg_stat_statements_top_max_exec_time_ms{pg_cluster=\"$cluster\",pod=~\"$pod\",dbname=~\"$datname\"}) without (instance,ip,query,queryid)",
     "legendFormat": "Max: {{exported_role}}({{dbname}})"
    }
   ]
  },
  {
   "title": "Row activity - $pod-$datname",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ccp_stat_database_tup_fetched{pg_cluster=\"$cluster\",pod=~\"$pod\",datname=~\"$datname\"}[5m]))",
     "legendFormat": "Fetched"
    },
    {
     "expr": "sum(irate(ccp_stat_database_tup_inserted{pg_cluster=\"$cluster\",pod=~\"$pod\",datname=~\"$datname\"}[5m]))",
     "legendFormat": "Inserted"
    },
    {
     "expr": "sum(irate(ccp_stat_database_tup_updated{pg_cluster=\"$cluster\",pod=~\"$pod\",datname=~\"$datname\"}[5m]))",
     "legendFormat": "Updated"
    },
    {
     "expr": "sum(irate(ccp_stat_database_tup_deleted{pg_cluster=\"$cluster\",pod=~\"$pod\",datname=~\"$datname\"}[5m]))",
     "legendFormat": "Deleted"
    },
    {
     "expr": "sum(irate(ccp_stat_database_tup_returned{pg_cluster=\"$cluster\",pod=~\"$pod\",datname=~\"$datname\"}[5m]))",
     "legendFormat": "Returned"
    }
   ]
  },
  {
   "title": "WAL size MB - $cluster-$pod",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "ccp_wal_activity_total_size_bytes{pg_cluster=\"$cluster\",pod=~\"$pod\"}/(1024*1024)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Key Counters - $pod - $datname",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ccp_stat_database_deadlocks{pg_cluster=\"$cluster\",pod=~\"$pod\",datname=~\"$datname\"}[5m]))",
     "legendFormat": "Conflicts"
    },
    {
     "expr": "sum(rate(ccp_stat_database_conflicts{pg_cluster=\"$cluster\",pod=~\"$pod\",datname=~\"$datname\"}[5m]))",
     "legendFormat": "DeadLocks"
    },
    {
     "expr": "sum(irate(ccp_stat_database_xact_commit{pg_cluster=\"$cluster\",pod=~\"$pod\",datname=~\"$datname\"}[5m]))",
     "legendFormat": "Commits"
    },
    {
     "expr": "sum(irate(ccp_stat_database_xact_rollback{pg_cluster=\"$cluster\",pod=~\"$pod\",datname=~\"$datname\"}[5m]))",
     "legendFormat": "Rollbacks"
    }
   ]
  },
  {
   "title": "Replication Lag - $cluster",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "Lag bytes" }
   ],
   "targets": [
    {
     "expr": "ccp_replication_lag_size_bytes{pg_cluster=\"$cluster\", role!=\"replica\"}",
     "legendFormat": "Bytes ({{replica}})"
    },
    {
     "expr": "ccp_replication_lag_replay_time{pg_cluster=\"$cluster\", role=\"replica\"}",
     "legendFormat": "Time ({{ip}})"
    }
   ]
  },
  {
   "title": "Buffers - $pod",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ccp_stat_bgwriter_buffers_alloc{pg_cluster=\"$cluster\",pod=~\"$pod\"})",
     "legendFormat": "Allocated"
    },
    {
     "expr": "sum(ccp_stat_bgwriter_buffers_backend{pg_cluster=\"$cluster\",pod=~\"$pod\"})",
     "legendFormat": "Backend"
    },
    {
     "expr": "sum(ccp_stat_bgwriter_buffers_backend_fsync{pg_cluster=\"$cluster\",pod=~\"$pod\"})",
     "legendFormat": "FSync"
    },
    {
     "expr": "sum(ccp_stat_bgwriter_buffers_checkpoint{pg_cluster=\"$cluster\",pod=~\"$pod\"})",
     "legendFormat": "CheckPoint"
    },
    {
     "expr": "sum(ccp_stat_bgwriter_buffers_clean{pg_cluster=\"$cluster\",pod=~\"$pod\"})",
     "legendFormat": "Clean"
    }
   ]
  },
  {
   "title": "Locks - $pod-$datname",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (ccp_locks_count{pg_cluster=\"$cluster\",pod=~\"$pod\",datname=~\"$datname\",mode=\"accessexclusivelock\"})",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (mode) (ccp_locks_count{pg_cluster=\"$cluster\",pod=~\"$pod\",datname=~\"$datname\",mode=\"exclusivelock\"})",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (mode) (ccp_locks_count{pg_cluster=\"$cluster\",pod=~\"$pod\",datname=~\"$datname\",mode=\"rowexclusivelock\"})",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (mode) (ccp_locks_count{pg_cluster=\"$cluster\",pod=~\"$pod\",datname=~\"$datname\",mode=\"sharerowexclusivelock\"})",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (mode) (ccp_locks_count{pg_cluster=\"$cluster\",pod=~\"$pod\",datname=~\"$datname\",mode=\"shareupdateexclusivelock\"})",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "sum by (mode) (ccp_locks_count{pg_cluster=\"$cluster\",pod=~\"$pod\",datname=~\"$datname\",mode=\"accesssharelock\"})",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio - $pod-$datname",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ccp_stat_database_blks_hit{pg_cluster=\"$cluster\",pod=~\"$pod\", dbname!~\"template0\", dbname!~\"template1\"}*100/(ccp_stat_database_blks_hit{pg_cluster=\"$cluster\",pod=~\"$pod\", dbname!~\"template0\", dbname!~\"template1\"} + ccp_stat_database_blks_read{pg_cluster=\"$cluster\",pod=~\"$pod\",dbname!~\"template0\", dbname!~\"template1\"})",
     "legendFormat": "{{dbname}} - ({{pod}})"
    }
   ]
  }
 ]
}