{
 "title": "Query Statistics",
 "tags": [ "vendor=crunchydata" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "pg_up" } },
   {
    "name": "role",
    "label": "service",
    "query": {
     "query": "label_values({pg_cluster=\"$cluster\"},role)"
    }
   },
   {
    "name": "dbname",
    "label": "dbname",
    "query": {
     "query": "label_values(ccp_database_size_bytes{pg_cluster=\"$cluster\"},dbname)"
    }
   },
   {
    "name": "dbuser",
    "label": "dbuser",
    "query": {
     "query": "label_values(ccp_pg_stat_statements_total_calls_count{pg_cluster=\"$cluster\", dbname=~\"$dbname\"},exported_role)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Queries Executed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(ccp_pg_stat_statements_total_calls_count{pg_cluster=\"$cluster\", role=\"$role\",dbname=~\"$dbname\",exported_role=~\"[[dbuser]]\"}[$__range])) without(instance, ip, deployment,pod,dbname,exported_role)"
    }
   ]
  },
  {
   "title": "Query Runtime ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(ccp_pg_stat_statements_total_exec_time_ms{pg_cluster=\"$cluster\", role=\"$role\",dbname=~\"$dbname\",exported_role=~\"[[dbuser]]\"}[$__range])) without(instance, ip, deployment,pod,dbname,exported_role)"
    }
   ]
  },
  {
   "title": "Query Mean Runtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(sum_over_time(ccp_pg_stat_statements_total_mean_exec_time_ms{pg_cluster=\"$cluster\", role=\"$role\",dbname=~\"$dbname\",exported_role=~\"[[dbuser]]\"}[$__range])) without(instance, ip, deployment,pod,dbname,exported_role)"
    }
   ]
  },
  {
   "title": "Rows Retrieved or Affected",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(ccp_pg_stat_statements_total_row_count{pg_cluster=\"$cluster\", role=\"$role\",dbname=~\"$dbname\",exported_role=~\"[[dbuser]]\"}[$__range])) without(instance, ip, deployment, pod,dbname,exported_role)"
    }
   ]
  },
  {
   "title": "Query Executions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(ccp_pg_stat_statements_total_calls_count{pg_cluster=\"$cluster\", role=\"$role\",dbname=~\"$dbname\",exported_role=~\"[[dbuser]]\"}[$__range])) without(instance, ip, deployment, pod)",
     "legendFormat": "db: {{dbname}}, user: {{exported_role}}"
    }
   ]
  },
  {
   "title": "Query Mean Runtime (Top N)",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg(avg_over_time(ccp_pg_stat_statements_top_mean_exec_time_ms{pg_cluster=\"$cluster\", role=\"$role\",dbname=~\"$dbname\",exported_role=~\"[[dbuser]]\"}[$__range])) without(instance, ip, deployment,pod)"
    }
   ]
  },
  {
   "title": "Query Max Runtime (Top N)",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "max(max_over_time(ccp_pg_stat_statements_top_max_exec_time_ms{pg_cluster=\"$cluster\", role=\"$role\",dbname=~\"$dbname\",exported_role=~\"[[dbuser]]\"}[$__range])) without(instance, ip, deployment,pod)"
    }
   ]
  },
  {
   "title": "Query Total Runtime (Top N)",
   "type": "table",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(irate(ccp_pg_stat_statements_top_total_exec_time_ms{pg_cluster=\"$cluster\", role=\"$role\",dbname=~\"$dbname\",exported_role=~\"[[dbuser]]\"}[$__range])) without(instance, ip, deployment,pod)"
    }
   ]
  }
 ]
}